### ISSUE TITLE
Getting `ENAMETOOLONG: name too long` when deploying

### ISSUE THREAD

**Issue by john** [awslabs/aws-rails-provisioner#12]
On Mac OS, it looks like it's trying to create a very long filename and hitting a limit. Output:

> aws-rails-provisioner deploy --init --cdk-directory cdk-uc

ENAMETOOLONG: name too long, lstat '/Users/johmcgr/repos/usecaser/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/cdk-uc/cdk.out/asset.4277fc160f06a74520bae4cfe28dfd18c5e79b701169cd2f31b397bf069d83d8/app/views/application/_asker_question_nav.html.haml'
Subprocess exited with error 1

**Comment by phstc** [comment]
Did you figure this out? I'm getting the same error.

**Comment by phstc** [comment]
This https://github.com/aws/aws-cdk/issues/3899#issuecomment-580394612 did the trick.

**Comment by mullermp** [comment]
This appears to be a CDK bug. Closing in favor of @phstc's findings.
