### ISSUE TITLE
cdk bootstrap

### ISSUE THREAD

**Issue by toneplex** [awslabs/aws-rails-provisioner#4]
The first time I ran `aws-rails-provisioner deploy`, I got the error message, `This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")`. 

After manually running `cdk bootstrap` I was able to proceed.

**Comment by toddwsullivan** [comment]
Same issue here.

**Comment by mullermp** [comment]
Hey - I'm sorry this is very late here; we've been short on hands the last 6 months. I've started picking up these issues. I have added `cdk bootstrap` as part of the deploy command to get around this on your behalf. I will get those changes in when I can.
