### ISSUE TITLE
aurora-postgresql DBParameterGroupFamily error

### ISSUE THREAD

**Issue by toneplex** [awslabs/aws-rails-provisioner#5]
When selecting postgresql 10.7 I run into an issue

```
aws-rails-provisioner.yml
...
    db_cluster:
      engine: aurora-postgresql
      engine_version: 10.7
...
```

I'm getting the following error 

`11/28 | 4:36:11 PM | CREATE_FAILED        | AWS::RDS::DBCluster                         | DBCluster (DBCluster15AF587F) The Parameter Group aws-rails-provisioner-default-aurora-postgresql with DBParameterGroupFamily aurora-postgresql9.6 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-postgresql10 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: ...)
`

**Comment by toneplex** [comment]
I was able to work around this by changing

```
const db = new rds.DatabaseCluster(this, 'DBCluster', {
            engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
            engineVersion: '10.7',
...
            parameterGroup: clusterParameterGroup,
        });
```

to



```
const db = new rds.DatabaseCluster(this, 'DBCluster', {
            engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
            engineVersion: '10.7',
...
            parameterGroup: {
                parameterGroupName: "default.aurora-postgresql10",
            },
        });
```

**Comment by toddwsullivan** [comment]
I think I'm getting a similar issue.

```
aws-rails-provisioner.yml
...
    db_cluster:
        engine: aurora-postgresql
        db_name: tsu_fargate
...

```
 11/26 | 1:56:39 PM | CREATE_FAILED        | AWS::RDS::DBCluster                       | DBCluster (DBCluster15AF587F) DBClusterParameterGroup not found: aws-rails-provisioner-default-aurora-postgresql (Service: AmazonRDS; Status Code: 404; Error Code: DBClusterParameterGroupNotFound; Request ID: 2cd0102a-9753-4d8a-8e6e-9976dd061977)

**Comment by mullermp** [comment]
Hey - I'm sorry this is very late here; we've been short on hands the last 6 months. I've started picking up these issues. The current code seems to have a hand maintained switch case (https://github.com/awslabs/aws-rails-provisioner/blob/master/lib/aws-rails-provisioner/db_cluster.rb#L226). I'm thinking that this can actually be passed in via configuration and if not I will look to add that.
